name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 20.x]
        zustand: [latest, next] # [latest, 4.2.0, 4.0.0, next]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Install Zustand ${{ matrix.zustand }}
        run: pnpm add zustand@${{ matrix.zustand }} -w

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test:ci